services:
  tn-calculator-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: |- 
      sh -c "
      pnpm i
      pnpm start:watch
      "
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      REDIS_URL: redis://redis:6379
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USER: calculator
      DB_PASSWORD: localpassword
    volumes:
      - .:/app
      - ./.pnpm:/root/.pnpm
      - ./.api_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: localpassword
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"