apiVersion: apps/v1
kind: Deployment
metadata:
  name: tn-calculator-api
  labels:
    app: tn-calculator-api
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: tn-calculator-api
  template:
    metadata:
      labels:
        app: tn-calculator-api
    spec:
      containers:
        - name: tn-calculator-api
          image: ghcr.io/femoral/tn-calculator-api
          imagePullPolicy: Always
          env:
            - name: 'NODE_ENV'
              value: 'production'
            - name: 'APP_PORT'
              value: '8080'
            - name: 'REDIS_URL'
              value: 'redis://redis-svc.commons.svc.cluster.local:6379'
            - name: "DB_HOST"
              value: "postgresql15-svc.commons.svc.cluster.local"
            - name: "DB_PORT"
              value: "5432"
            - name: "DB_DATABASE"
              value: "postgres"
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: "postgre15-calculator-secret"
                  key: "username"
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "postgre15-calculator-secret"
                  key: "password"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tn-calculator-api-http-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: tn-calculator-api